# Generated by Django 5.0.6 on 2024-06-26 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mac', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hub_status',
            old_name='mac_id',
            new_name='mac_address',
        ),
    ]
