# Generated by Django 5.0.6 on 2024-07-05 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mac', '0002_rename_mac_id_hub_status_mac_address'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='hub_status',
            new_name='HubStatus',
        ),
        migrations.AlterModelOptions(
            name='hubstatus',
            options={'verbose_name': 'Hub Status', 'verbose_name_plural': 'Hub Statuses'},
        ),
    ]
